application: organise-asana
version: 2
runtime: php55
api_version: 1

handlers:
- url: /tasks/process
  script: process.php
  login: admin
- url: /
  script: index.php
# All URLs ending in .gif .png or .jpg are treated as paths to static files in
# the static/ directory. The URL pattern is a regexp, with a grouping that is
# inserted into the path to the file.
- url: /(.*\.(gif|png|jpg|ico|css|js|txt))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|ico|css|js|txt)$
